### ISSUE TITLE
Website Issue Tracking

### ISSUE THREAD

**Issue by NeuralSandwich** [NapierDevSoc/NapierDevSoc.github.io#9]
### Things that need done on the website

- [ ] All link on the nav bar need created
- [ ] Images need sourced for the slide orbiter on the home page
- [ ] Needs to be made mobile friendly
- [ ] Need to create content for website

**Comment by wyrdathru** [comment]
Legacy issue, closing.
